[tool.poetry]
name = "practiceenv"
version = "0.1.0"
description = ""
authors = ["dkyoon <dkyoon@agilesoda.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.23.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
